import type { ChordDefinition } from './types';

export const CHORD_DIAGRAMS: Record<string, ChordDefinition> = {
  'A': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 2, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'A_V2': {
    positions: [
      { fret: 5, string: 6 },
      { fret: 7, string: 5 },
      { fret: 7, string: 4 },
      { fret: 6, string: 3 },
      { fret: 5, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [{ fret: 5, startString: 6, endString: 1 }],
  },
  'Am': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Am_V2': {
    positions: [
      { fret: 5, string: 6 },
      { fret: 7, string: 5 },
      { fret: 7, string: 4 },
      { fret: 5, string: 3 },
      { fret: 5, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [{ fret: 5, startString: 6, endString: 1 }],
  },
  'Bb': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 1, string: 5 },
      { fret: 3, string: 4 },
      { fret: 3, string: 3 },
      { fret: 3, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [
      { fret: 1, startString: 5, endString: 1 },
      { fret: 3, startString: 4, endString: 2 },
    ],
  },
  'Bb_V2': {
    positions: [
      { fret: 6, string: 6 },
      { fret: 8, string: 5 },
      { fret: 8, string: 4 },
      { fret: 7, string: 3 },
      { fret: 6, string: 2 },
      { fret: 6, string: 1 },
    ],
    barres: [{ fret: 6, startString: 6, endString: 1 }],
  },
  'Bbm': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 1, string: 5 },
      { fret: 3, string: 4 },
      { fret: 3, string: 3 },
      { fret: 2, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 5, endString: 1 }],
  },
  'B': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 4, string: 4 },
      { fret: 4, string: 3 },
      { fret: 4, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [
      { fret: 2, startString: 5, endString: 1 },
      { fret: 4, startString: 4, endString: 2 },
    ],
  },
  'B_V2': {
    positions: [
      { fret: 7, string: 6 },
      { fret: 9, string: 5 },
      { fret: 9, string: 4 },
      { fret: 8, string: 3 },
      { fret: 7, string: 2 },
      { fret: 7, string: 1 },
    ],
    barres: [{ fret: 7, startString: 6, endString: 1 }],
  },
  'Bm': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 4, string: 4 },
      { fret: 4, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [{ fret: 2, startString: 5, endString: 1 }],
  },
  'C': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'C_V2': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 5, string: 3 },
      { fret: 5, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [
      { fret: 3, startString: 5, endString: 1 },
      { fret: 5, startString: 4, endString: 2 },
    ],
  },
  'C_V3': {
    positions: [
      { fret: 8, string: 6 },
      { fret: 10, string: 5 },
      { fret: 10, string: 4 },
      { fret: 9, string: 3 },
      { fret: 8, string: 2 },
      { fret: 8, string: 1 },
    ],
    barres: [{ fret: 8, startString: 6, endString: 1 }],
  },
  'Cm': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [{ fret: 3, startString: 5, endString: 1 }],
  },
  'C#': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 4, string: 5 },
      { fret: 6, string: 4 },
      { fret: 6, string: 3 },
      { fret: 6, string: 2 },
      { fret: 4, string: 1 },
    ],
    barres: [
      { fret: 4, startString: 5, endString: 1 },
      { fret: 6, startString: 4, endString: 2 },
    ],
  },
  'C#m': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 4, string: 5 },
      { fret: 6, string: 4 },
      { fret: 6, string: 3 },
      { fret: 5, string: 2 },
      { fret: 4, string: 1 },
    ],
    barres: [{ fret: 4, startString: 5, endString: 1 }],
  },
  'D': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'D_V2': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 5, string: 5 },
      { fret: 7, string: 4 },
      { fret: 7, string: 3 },
      { fret: 7, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [
      { fret: 5, startString: 5, endString: 1 },
      { fret: 7, startString: 4, endString: 2 },
    ],
  },
  'Dm': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [],
  },
  'Eb': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 6, string: 5 },
      { fret: 8, string: 4 },
      { fret: 8, string: 3 },
      { fret: 8, string: 2 },
      { fret: 6, string: 1 },
    ],
    barres: [
      { fret: 6, startString: 5, endString: 1 },
      { fret: 8, startString: 4, endString: 2 },
    ],
  },
  'Ebm': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 6, string: 5 },
      { fret: 8, string: 4 },
      { fret: 8, string: 3 },
      { fret: 7, string: 2 },
      { fret: 6, string: 1 },
    ],
    barres: [{ fret: 6, startString: 5, endString: 1 }],
  },
  'E': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 2, string: 4 },
      { fret: 1, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Em': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'F': {
    positions: [
      { fret: 1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 3, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 6, endString: 1 }],
  },
  'Fm': {
    positions: [
      { fret: 1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 3, string: 4 },
      { fret: 1, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 6, endString: 1 }],
  },
  'F#': {
    positions: [
      { fret: 2, string: 6 },
      { fret: 4, string: 5 },
      { fret: 4, string: 4 },
      { fret: 3, string: 3 },
      { fret: 2, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [{ fret: 2, startString: 6, endString: 1 }],
  },
  'F#m': {
    positions: [
      { fret: 2, string: 6 },
      { fret: 4, string: 5 },
      { fret: 4, string: 4 },
      { fret: 2, string: 3 },
      { fret: 2, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [{ fret: 2, startString: 6, endString: 1 }],
  },
  'G': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [],
  },
  'G_V2': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 5, string: 5 },
      { fret: 5, string: 4 },
      { fret: 4, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [{ fret: 3, startString: 6, endString: 1 }],
  },
  'Gm': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 5, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [{ fret: 3, startString: 6, endString: 1 }],
  },
  'G#': {
    positions: [
      { fret: 4, string: 6 },
      { fret: 6, string: 5 },
      { fret: 6, string: 4 },
      { fret: 5, string: 3 },
      { fret: 4, string: 2 },
      { fret: 4, string: 1 },
    ],
    barres: [{ fret: 4, startString: 6, endString: 1 }],
  },
  'G#m': {
    positions: [
      { fret: 4, string: 6 },
      { fret: 6, string: 5 },
      { fret: 6, string: 4 },
      { fret: 4, string: 3 },
      { fret: 4, string: 2 },
      { fret: 4, string: 1 },
    ],
    barres: [{ fret: 4, startString: 6, endString: 1 }],
  },
  'A7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 2, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Amaj7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 1, string: 3 },
      { fret: 2, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Am7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'B7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 1, string: 4 },
      { fret: 2, string: 3 },
      { fret: 0, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'Bmaj7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 4, string: 4 },
      { fret: 3, string: 3 },
      { fret: 4, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [
      { fret: 2, startString: 5, endString: 1 },
      { fret: 4, startString: 4, endString: 2 },
    ],
  },
  'Bm7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 4, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [{ fret: 2, startString: 5, endString: 1 }],
  },
  'C7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 3, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Cmaj7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Cm7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 4, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [{ fret: 3, startString: 5, endString: 1 }],
  },
  'D7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'Dmaj7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 2, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'Dm7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [],
  },
  'E7': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 1, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Emaj7': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 1, string: 4 },
      { fret: 1, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Em7': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'F7': {
    positions: [
      { fret: 1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 1, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 6, endString: 1 }],
  },
  'Fmaj7': {
    positions: [
      { fret: 1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 6, endString: 1 }],
  },
  'Fm7': {
    positions: [
      { fret: 1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 1, string: 4 },
      { fret: 1, string: 3 },
      { fret: 1, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [{ fret: 1, startString: 6, endString: 1 }],
  },
  'G7': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [],
  },
  'Gmaj7': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 2, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'Gm7': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 5, string: 5 },
      { fret: 3, string: 4 },
      { fret: 3, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [{ fret: 3, startString: 6, endString: 1 }],
  },
  'Asus4': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Asus2': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Aadd9': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 2, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Dsus4': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [],
  },
  'Dsus2': {
    positions: [
      { fret: -1, string: 6 },
      { fret: -1, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Esus4': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 0, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'Gsus4': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 5, string: 5 },
      { fret: 5, string: 4 },
      { fret: 5, string: 3 },
      { fret: 3, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [
      { fret: 3, startString: 6, endString: 1 },
      { fret: 5, startString: 5, endString: 3 },
    ],
  },
  'A9': {
    positions: [
      { fret: 5, string: 6 },
      { fret: 4, string: 5 },
      { fret: 5, string: 4 },
      { fret: 4, string: 3 },
      { fret: 5, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'Am9': {
    positions: [
      { fret: 5, string: 6 },
      { fret: 3, string: 5 },
      { fret: 5, string: 4 },
      { fret: 4, string: 3 },
      { fret: 5, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'Cmaj9': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 4, string: 3 },
      { fret: 3, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'D9': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 5, string: 5 },
      { fret: 4, string: 4 },
      { fret: 5, string: 3 },
      { fret: 5, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [{ fret: 5, startString: 2, endString: 1 }],
  },
  'Dm9': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 5, string: 5 },
      { fret: 3, string: 4 },
      { fret: 5, string: 3 },
      { fret: 5, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [{ fret: 5, startString: 2, endString: 1 }],
  },
  'E9': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 1, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'Em9': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'G13': {
    positions: [
      { fret: 3, string: 6 },
      { fret: -1, string: 5 },
      { fret: 3, string: 4 },
      { fret: 4, string: 3 },
      { fret: 5, string: 2 },
      { fret: 5, string: 1 },
    ],
    barres: [{ fret: 5, startString: 2, endString: 1 }],
  },
  'Adim7': {
    positions: [
      { fret: 5, string: 6 },
      { fret: 4, string: 5 },
      { fret: 5, string: 4 },
      { fret: 3, string: 3 },
      { fret: 5, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'Aaug': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 0, string: 5 },
      { fret: 3, string: 4 },
      { fret: 2, string: 3 },
      { fret: 2, string: 2 },
      { fret: 1, string: 1 },
    ],
    barres: [],
  },
  'Bdim': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 3, string: 4 },
      { fret: 4, string: 3 },
      { fret: 3, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'Cdim7': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 4, string: 4 },
      { fret: 2, string: 3 },
      { fret: 4, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'Caug': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 1, string: 3 },
      { fret: 1, string: 2 },
      { fret: -1, string: 1 },
    ],
    barres: [],
  },
  'C/E': {
    positions: [
      { fret: 0, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'C/G': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 3, string: 5 },
      { fret: 2, string: 4 },
      { fret: 0, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
  'D/F#': {
    positions: [
      { fret: 2, string: 6 },
      { fret: 0, string: 5 },
      { fret: 0, string: 4 },
      { fret: 2, string: 3 },
      { fret: 3, string: 2 },
      { fret: 2, string: 1 },
    ],
    barres: [],
  },
  'G/B': {
    positions: [
      { fret: -1, string: 6 },
      { fret: 2, string: 5 },
      { fret: 0, string: 4 },
      { fret: 0, string: 3 },
      { fret: 0, string: 2 },
      { fret: 3, string: 1 },
    ],
    barres: [],
  },
  'Am/G': {
    positions: [
      { fret: 3, string: 6 },
      { fret: 0, string: 5 },
      { fret: 2, string: 4 },
      { fret: 2, string: 3 },
      { fret: 1, string: 2 },
      { fret: 0, string: 1 },
    ],
    barres: [],
  },
};
